.\" changepass 1.0.0
.\"
.TH CHANGEPASS 8 "DEC 29, 2006"
.AT 8
.SH NAME
    \fBchangepass\fP \- update an user's password

.SH SYNOPSIS
    changepass
    
.SH DESCRIPTION
\fBchangepass\fP is a chpasswd clone, it might be useful on 
platforms that doesn't have such a command like Solaris.
.br.br
Most GNU/Linux distributions have chpasswd (8), on FreeBSD 
you can use "pw usermod name -h 0" but many commercial Un*ces
doesn't have tool like this.  An alternative is to update the 
user's password in script with \fBusermod\fP
.br.br
but it's possible to see the encrypted password in the process
list, which is not very secure.
.br.br
\fBchangepass\fP reads a list of user name and password pairs
from \fBstdin\fP  and updates the users passwords
.br.br
Each line has format:
.br.
username:password
.br    
.SH OPTIONS
.br
   -h,--help    print this help
   -n,--nopam   don't use pam
   -p,--pam     use pam (default)
   -e,--encrypt password is already encrypted, this option
.br             will disable pam
   -m,--md5     use md5 encryption, this option will
.br             disable pam
   -v,--verbose enable verbose output

.br    
.SH USAGE
.br 
cat user_password_pairs | changepass
.br

.SH AUTHOR
Written by Staf Wagemakers <staf@wagemakers.be>
    
.SH COPYRIGHT
Copyright (c)2002, 2006 Staf Wagemakers.
.br    
You are free to distribute this software under the terms of the 
GNU General Public License. The complete text of the GNU General
Public License can be found at http://www.gnu.org/licenses/gpl.html
.br
