<HR>
<P>
<FORM ACTION="/cgi-bin/viewmailcfg.cgi" METHOD=POST>
<TABLE WIDTH=80%>
<TR>
<TD bgcolor="#B0B0B0" WIDTH=20%>Login name:</TD>
<TD ALIGN="CENTER"><INPUT NAME=name TYPE=TEXT SIZE=10 MAXLENGTH=15 VALUE="<? echo $name ?>"></TD>
<TD WIDTH=20%>password :</TD>
<TD><INPUT NAME=passwd TYPE=PASSWORD SIZE=8 MAXLENGTH=10></TD>
</TR>
</TABLE>
<HR>
<CENTER>
<TABLE>
<TD>
<INPUT TYPE=RESET VALUE="Clear">
</TD>
<TD>
<INPUT TYPE=SUBMIT VALUE="Submit">
</TD>
</TABLE>
</CENTER>
</FORM>
</BODY>
